baseurl = "/"
languageCode = "en-us"
title = "Huntington Underwriting Limited"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Disclaimer"
    url = "/disclaimer/"
[[menu.main]]
    name = "Regulation"
    url = "/regulation/"
[[menu.main]]
    name = "Solutions"
    url = "/structured/"
[[menu.main]]
    name = "Contact"
    url = "/contact/" 


[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 100
    height = 100
    alt = "Logo"

